### ISSUE TITLE
ops.model.ModelError: ERROR permission denied

### ISSUE THREAD

**Issue by juditnovak** [canonical/tls-certificates-interface#202]
### Bug Description

Failure `hook failed: "certificates-relation-changed"`

### To Reproduce

See all details on https://github.com/canonical/opensearch-dashboards-operator/actions/runs/9905318848/job/27364829899#step:22:280

### Environment

See all details on https://github.com/canonical/opensearch-dashboards-operator/actions/runs/9905318848/job/27364829899#step:22:280

### Relevant log output

```shell
Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.3    unsupported  09:18:32Z

App                       Version  Status   Scale  Charm                     Channel        Rev  Exposed  Message
application                        unknown      1  application                                0  no       
opensearch                         error        2  opensearch                2/edge         114  no       hook failed: "certificates-relation-changed"
opensearch-dashboards              blocked      3  opensearch-dashboards                      0  no       Opensearch connection is missing
self-signed-certificates           active       1  self-signed-certificates  latest/stable  155  no       

Unit                         Workload     Agent      Machine  Public address  Ports     Message
application/0*               unknown      idle       3        10.72.72.203              
opensearch-dashboards/0      active       idle       0        10.72.72.9      5601/tcp  
opensearch-dashboards/1*     active       idle       1        10.72.72.68     5601/tcp  
opensearch-dashboards/2      active       idle       2        10.72.72.224    5601/tcp  
opensearch/0                 error        idle       5        10.72.72.249              hook failed: "certificates-relation-changed"
opensearch/1*                maintenance  executing  6        10.72.72.165              Waiting for TLS to be fully configured...
self-signed-certificates/0*  active       executing  4        10.72.72.4                
```

```
unit-opensearch-0: 09:18:31 ERROR unit.opensearch/0.juju-log certificates:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/model.py", line 3180, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-opensearch-0/secret-get', '--label', 'opensearch:app:app-admin', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 548, in main
    manager.run()
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 527, in run
    self._emit()
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 516, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/tls_certificates_interface/v3/tls_certificates.py", line 1811, in _on_relation_changed
    self.on.certificate_available.emit(
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_tls.py", line 209, in _on_certificate_available
    self.store_new_ca(self.charm.secrets.get_object(scope, cert_type.val))
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_tls.py", line 444, in store_new_ca
    self._create_keystore_pwd_if_not_exists(Scope.APP, CertType.APP_ADMIN, "ca")
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_tls.py", line 427, in _create_keystore_pwd_if_not_exists
    secrets = self.charm.secrets.get_object(scope, cert_type.val)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_secrets.py", line 331, in get_object
    return self._get_juju_secret_content(scope, key)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_secrets.py", line 210, in _get_juju_secret_content
    secret = self._get_juju_secret(scope, key)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_secrets.py", line 198, in _get_juju_secret
    secret = self._charm.model.get_secret(label=label)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/model.py", line 291, in get_secret
    content = self._backend.secret_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/model.py", line 3545, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/model.py", line 3182, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR permission denied
```
```


### Additional context

Clearly the issue is not on the lib's side. However it may be good to protect against it in the lib...

**Comment by juditnovak** [comment]
Sry, false alarm.
