### ISSUE TITLE
Backward incompatible change in v3

### ISSUE THREAD

**Issue by cbartz** [canonical/tls-certificates-interface#228]
### Bug Description

The change introduced in https://github.com/canonical/tls-certificates-interface/pull/188 is backward incompatible. When a secret created by an earlier version of the library expires, it does not contain the key "csr", so the `secret expirde` hook fails. See also https://github.com/canonical/nginx-ingress-integrator-operator/issues/162.

### To Reproduce

See reproduction steps at https://github.com/canonical/nginx-ingress-integrator-operator/issues/162 

### Environment

juju 3.1

### Relevant log output

```shell
unit-nginx-ingress-integrator-0: 11:13:27 DEBUG unit.nginx-ingress-integrator/0.juju-log Emitting Juju event secret_expired.
unit-nginx-ingress-integrator-0: 11:13:27 ERROR unit.nginx-ingress-integrator/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 557, in <module>
    main(NginxIngressCharm)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/lib/charms/tls_certificates_interface/v3/tls_certificates.py", line 1971, in _on_secret_expired
    csr = event.secret.get_content()["csr"]
KeyError: 'csr'
unit-nginx-ingress-integrator-0: 11:13:27 ERROR juju.worker.uniter.operation hook "secret-expired" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by gruyaume** [comment]
Thank you for reporting this issue @cbartz, we definitely need better upgrade testing here (and in the charm ecosystem in general)

**Comment by PietroPasotti** [comment]
@saltiyazan still facing this with the updated library revision

**Comment by PietroPasotti** [comment]
![image](https://github.com/user-attachments/assets/7f94415d-ef48-4338-9233-b32cedf1bd79)

**Comment by PietroPasotti** [comment]
this is the status-log for the failing unit. looks like it's processing secret-changed for revision 1 well, but starting to error out on revision 2.
perhaps it mistakenly deletes the secret during the first hook and then fails to find it in the second?
![image](https://github.com/user-attachments/assets/3b1e0128-68b3-4e8b-bc01-45e891fd8a24)

**Comment by saltiyazan** [comment]
Thanks for reporting this @PietroPasotti. I'll look into it.

**Comment by PietroPasotti** [comment]
Ehm, sorry but we're back to being broken because the latest change in #262 breaks support with earlier python typing:

![image](https://github.com/user-attachments/assets/bafb3ad5-8618-407e-b319-254c8feef628)
